image: docker:git
stages:
    - build
    - build-test
    - test
    - publish
    - make_bundle

variables:
  GIT_SUBMODULE_STRATEGY: normal
  TESTENV_IMAGE: "${CI_REGISTRY_IMAGE}/testenv:${CI_PIPELINE_ID}"

before_script:
  - set -u
  - (which docker && docker login -u ${CI_REGISTRY_USER} -p ${CI_BUILD_TOKEN} ${CI_REGISTRY}) || true
  - export GIT_PRETTY_REF=`git describe --always --tag`

#######################
# Base Job definitions
#######################
.docker-image: &docker-image
    stage: build
    script:
        - docker build -f docker/Dockerfile -t ${IMAGE} --label com.lgsvlsimulator.scenarios_runner.build_ref=${GIT_PRETTY_REF} .
        - docker push ${IMAGE}
    tags:
        - docker

.bundle: &bundle
    image: docker:git
    stage: make_bundle
    script:
        - apk --no-cach add bash zip tree
        - docker pull ${IMAGE}
        - ./ci/make_bundle.sh ${IMAGE_TAG} ${CI_REGISTRY_IMAGE}
        - mv dist/lgsvlsimulator-scenarios-${IMAGE_TAG} .
    tags:
        - docker

.latest-job: &latest-job
    variables:
        IMAGE_TAG: latest
        IMAGE: ${CI_REGISTRY_IMAGE}:latest
    only:
        - master
        - ci-master

.tag-job: &tag-job
    only:
        - tags
    variables:
        IMAGE_TAG: ${CI_COMMIT_TAG}
        IMAGE: ${CI_REGISTRY_IMAGE}:${CI_COMMIT_TAG}

.branch-job: &branch-job
    variables:
        IMAGE: ${CI_REGISTRY_IMAGE}/${CI_COMMIT_REF_SLUG}:latest
    except:
        - master
        - ci-master
    only:
        - branches

########
# Jobs
########


## Build docker Images
docker-image-latest:
    <<: *docker-image
    <<: *latest-job

docker-image-tag:
    <<: *docker-image
    <<: *tag-job

docker-image-branch:
    <<: *docker-image
    <<: *branch-job

build-test-image:
    stage: build-test
    script:
        - docker build -f docker/Dockerfile -t ${CI_REGISTRY_IMAGE}/base .
        - docker build -f docker/Dockerfile.devenv -t ${TESTENV_IMAGE} --build-arg BASE_IMAGE=${CI_REGISTRY_IMAGE}/base .
        - docker push ${TESTENV_IMAGE}
    tags:
        - docker
    except:
        - ci-master

## Run tests

pytest:
    stage: test
    image: ${TESTENV_IMAGE}
    script:
        - pytest -s -v runner/tests
    tags:
        - docker
    except:
        - ci-master


## Bundles

bundle-latest:
    <<: *bundle
    <<: *latest-job
    artifacts:
        name: "lgsvlsimulator-scenarios-${IMAGE_TAG}"
        paths:
            - "lgsvlsimulator-scenarios-${IMAGE_TAG}"
        expire_in: 2 weeks

bundle-tag:
    <<: *bundle
    <<: *tag-job
    artifacts:
        name: "lgsvlsimulator-scenarios-${IMAGE_TAG}"
        paths:
            - "lgsvlsimulator-scenarios-${IMAGE_TAG}"
        expire_in: 2 months
    except:
        - CI_TAG

bundle-ci-tag:
    <<: *bundle
    <<: *tag-job
    artifacts:
        name: "lgsvlsimulator-scenarios-${IMAGE_TAG}"
        paths:
            - "lgsvlsimulator-scenarios-${IMAGE_TAG}"
        expire_in: 2 days
    only:
        - CI_TAG

.x-disabled-bundle-branch:
    <<: *bundle
    <<: *branch-job
    artifacts:
        name: "lgsvlsimulator-scenarios-${IMAGE_TAG}"
        paths:
            - "lgsvlsimulator-scenarios-${IMAGE_TAG}"
        expire_in: 2 days
