image: docker:git
stages:
    - build
    - test
    - publish

variables:
  GIT_SUBMODULE_STRATEGY: normal
  TESTENV_IMAGE: "${CI_REGISTRY_IMAGE}/testenv:${CI_PIPELINE_ID}"

before_script:
  - which docker && test -n "${CI_BUILD_TOKEN}" && docker login -u ${CI_REGISTRY_USER} -p ${CI_BUILD_TOKEN} ${CI_REGISTRY}
  - export GIT_PRETTY_REF=`git describe --always --tag`

build-image-latest:
    stage: build
    script:
        - ./ci/update-docker-image-ref.sh ${CI_REGISTRY_IMAGE}:latest
        - docker build -f docker/Dockerfile -t ${CI_REGISTRY_IMAGE}:latest --label build_ref=${GIT_PRETTY_REF} .
    only:
        - master
        - ci-master
    tags:
        - docker

build-image-branch:
    stage: build
    script:
        - ./ci/update-docker-image-ref.sh ${CI_REGISTRY_IMAGE}/${CI_COMMIT_REF_SLUG}:latest
        - docker build -f docker/Dockerfile -t ${CI_REGISTRY_IMAGE}/${CI_COMMIT_REF_SLUG}:latest --label build_ref=${GIT_PRETTY_REF} .
    only:
        - branches
    except:
        - master
    tags:
        - docker

build-test-image:
    stage: build
    script:
        - docker build -f docker/Dockerfile -t ${CI_REGISTRY_IMAGE}/base .
        - docker build -f docker/Dockerfile.devenv -t ${TESTENV_IMAGE} --build-arg BASE_IMAGE=${CI_REGISTRY_IMAGE}/base .
        - docker push ${TESTENV_IMAGE}
    tags:
        - docker

pytest:
    stage: test
    image: ${TESTENV_IMAGE}
    script:
        - pytest -s -v runner/tests
    tags:
        - docker

publish-image-latest:
    stage: publish
    script:
        - docker push ${CI_REGISTRY_IMAGE}:latest
    only:
        - master
        - ci-master
    tags:
        - docker

publish-image-branch:
    stage: publish
    script:
        - docker push ${CI_REGISTRY_IMAGE}/${CI_COMMIT_REF_SLUG}:latest
    only:
        - branches
    except:
        - master
    tags:
        - docker

