image: docker:git
stages:
    - build
    - publish

variables:
  GIT_SUBMODULE_STRATEGY: normal

before_script:
  - which docker && test -n "${CI_BUILD_TOKEN}" && docker login -u ${CI_REGISTRY_USER} -p ${CI_BUILD_TOKEN} ${CI_REGISTRY}

build-image-latest:
    stage: build
    script:
        - docker build -f docker/Dockerfile -t ${CI_REGISTRY_IMAGE}:latest .
    only:
        - master
        - ci-master
    tags:
        - docker

publish-image-latest:
    stage: publish
    script:
        - docker push ${CI_REGISTRY_IMAGE}:latest
    only:
        - master
        - ci-master
    tags:
        - docker
