image: docker:git
stages:
    - check-updates

variables:
  GIT_SUBMODULE_STRATEGY: normal
  TESTENV_IMAGE: "${CI_REGISTRY_IMAGE}/testenv:${CI_PIPELINE_ID}"

before_script:
  - set -u
  - (which docker && docker login -u ${CI_REGISTRY_USER} -p ${CI_BUILD_TOKEN} ${CI_REGISTRY}) || true
  - export GIT_PRETTY_REF=`git describe --always --tag`

## Check submodule updates

check-submodule-updates:
    stage: check-updates
    variables:
        GIT_AUTHOR_NAME: ${GITLAB_USER_NAME}
        GIT_AUTHOR_EMAIL: ${GITLAB_USER_EMAIL}
        GIT_COMMITTER_NAME: gitlab
        GIT_COMMITTER_EMAIL: gitlab@auto-gitlab.lgsvl.net
    script:
        - url_host=`git remote get-url origin | sed -e "s/https:\/\/gitlab-ci-token:.*@//g"`
        - git remote set-url origin "https://gitlab-ci-token:${CI_TAG_UPLOAD_TOKEN}@${url_host}"
        - apk --no-cach add git-lfs
        - ./ci/update-commit-git-submodules.sh submodule-autoupdate-${CI_PIPELINE_ID}
    only:
        - master
        - ci-master
    tags:
        - docker
