version: "3.3"
services:
    base:
        build:
            context: ..
            dockerfile: docker/Dockerfile
            labels:
                com.lgsvlsimulator.scenarios_runner.build_ref: ${BUILD_REF}
        image: scenario-runner-base

    devenv:
        build:
            context: ..
            dockerfile: docker/Dockerfile.devenv
            args:
                BASE_IMAGE: scenario-runner-base

        working_dir: /src
        network_mode: host
        volumes:
            - ..:/src:ro
        environment:
            - SIMULATOR_HOST
            - SIMULATOR_PORT
            - BRIDGE_HOST
            - BRIDGE_PORT
            - PYTHONPATH=/src/runner


