# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: autoware_vehicle_msgs.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import std_msgs_pb2 as std__msgs__pb2
import autoware_control_msgs_pb2 as autoware__control__msgs__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='autoware_vehicle_msgs.proto',
  package='autoware_vehicle_msgs',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x1b\x61utoware_vehicle_msgs.proto\x12\x15\x61utoware_vehicle_msgs\x1a\x0estd_msgs.proto\x1a\x1b\x61utoware_control_msgs.proto\"=\n\x05Shift\x12\x34\n\x04\x64\x61ta\x18\x01 \x01(\x0e\x32&.autoware_vehicle_msgs.SHIFT_POSITIONS\"\xaa\x01\n\x0eVehicleCommand\x12 \n\x06header\x18\x01 \x01(\x0b\x32\x10.std_msgs.Header\x12\x36\n\x07\x63ontrol\x18\x02 \x01(\x0b\x32%.autoware_control_msgs.ControlCommand\x12+\n\x05shift\x18\x03 \x01(\x0b\x32\x1c.autoware_vehicle_msgs.Shift\x12\x11\n\temergency\x18\x04 \x01(\x05*V\n\x0fSHIFT_POSITIONS\x12\x08\n\x04NONE\x10\x00\x12\x0b\n\x07PARKING\x10\x01\x12\x0b\n\x07REVERSE\x10\x02\x12\x0b\n\x07NEUTRAL\x10\x03\x12\t\n\x05\x44RIVE\x10\x04\x12\x07\n\x03LOW\x10\x05\x62\x06proto3')
  ,
  dependencies=[std__msgs__pb2.DESCRIPTOR,autoware__control__msgs__pb2.DESCRIPTOR,])

_SHIFT_POSITIONS = _descriptor.EnumDescriptor(
  name='SHIFT_POSITIONS',
  full_name='autoware_vehicle_msgs.SHIFT_POSITIONS',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='NONE', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PARKING', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='REVERSE', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='NEUTRAL', index=3, number=3,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DRIVE', index=4, number=4,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='LOW', index=5, number=5,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=335,
  serialized_end=421,
)
_sym_db.RegisterEnumDescriptor(_SHIFT_POSITIONS)

SHIFT_POSITIONS = enum_type_wrapper.EnumTypeWrapper(_SHIFT_POSITIONS)
NONE = 0
PARKING = 1
REVERSE = 2
NEUTRAL = 3
DRIVE = 4
LOW = 5



_SHIFT = _descriptor.Descriptor(
  name='Shift',
  full_name='autoware_vehicle_msgs.Shift',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='data', full_name='autoware_vehicle_msgs.Shift.data', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=99,
  serialized_end=160,
)


_VEHICLECOMMAND = _descriptor.Descriptor(
  name='VehicleCommand',
  full_name='autoware_vehicle_msgs.VehicleCommand',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='header', full_name='autoware_vehicle_msgs.VehicleCommand.header', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='control', full_name='autoware_vehicle_msgs.VehicleCommand.control', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='shift', full_name='autoware_vehicle_msgs.VehicleCommand.shift', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='emergency', full_name='autoware_vehicle_msgs.VehicleCommand.emergency', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=163,
  serialized_end=333,
)

_SHIFT.fields_by_name['data'].enum_type = _SHIFT_POSITIONS
_VEHICLECOMMAND.fields_by_name['header'].message_type = std__msgs__pb2._HEADER
_VEHICLECOMMAND.fields_by_name['control'].message_type = autoware__control__msgs__pb2._CONTROLCOMMAND
_VEHICLECOMMAND.fields_by_name['shift'].message_type = _SHIFT
DESCRIPTOR.message_types_by_name['Shift'] = _SHIFT
DESCRIPTOR.message_types_by_name['VehicleCommand'] = _VEHICLECOMMAND
DESCRIPTOR.enum_types_by_name['SHIFT_POSITIONS'] = _SHIFT_POSITIONS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Shift = _reflection.GeneratedProtocolMessageType('Shift', (_message.Message,), dict(
  DESCRIPTOR = _SHIFT,
  __module__ = 'autoware_vehicle_msgs_pb2'
  # @@protoc_insertion_point(class_scope:autoware_vehicle_msgs.Shift)
  ))
_sym_db.RegisterMessage(Shift)

VehicleCommand = _reflection.GeneratedProtocolMessageType('VehicleCommand', (_message.Message,), dict(
  DESCRIPTOR = _VEHICLECOMMAND,
  __module__ = 'autoware_vehicle_msgs_pb2'
  # @@protoc_insertion_point(class_scope:autoware_vehicle_msgs.VehicleCommand)
  ))
_sym_db.RegisterMessage(VehicleCommand)


# @@protoc_insertion_point(module_scope)
