# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: autoware_control_msgs.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='autoware_control_msgs.proto',
  package='autoware_control_msgs',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x1b\x61utoware_control_msgs.proto\x12\x15\x61utoware_control_msgs\"q\n\x0e\x43ontrolCommand\x12\x16\n\x0esteering_angle\x18\x01 \x01(\x01\x12\x1f\n\x17steering_angle_velocity\x18\x02 \x01(\x01\x12\x10\n\x08velocity\x18\x03 \x01(\x01\x12\x14\n\x0c\x61\x63\x63\x65leration\x18\x04 \x01(\x01\x62\x06proto3')
)




_CONTROLCOMMAND = _descriptor.Descriptor(
  name='ControlCommand',
  full_name='autoware_control_msgs.ControlCommand',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='steering_angle', full_name='autoware_control_msgs.ControlCommand.steering_angle', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='steering_angle_velocity', full_name='autoware_control_msgs.ControlCommand.steering_angle_velocity', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='velocity', full_name='autoware_control_msgs.ControlCommand.velocity', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='acceleration', full_name='autoware_control_msgs.ControlCommand.acceleration', index=3,
      number=4, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=54,
  serialized_end=167,
)

DESCRIPTOR.message_types_by_name['ControlCommand'] = _CONTROLCOMMAND
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ControlCommand = _reflection.GeneratedProtocolMessageType('ControlCommand', (_message.Message,), dict(
  DESCRIPTOR = _CONTROLCOMMAND,
  __module__ = 'autoware_control_msgs_pb2'
  # @@protoc_insertion_point(class_scope:autoware_control_msgs.ControlCommand)
  ))
_sym_db.RegisterMessage(ControlCommand)


# @@protoc_insertion_point(module_scope)
