# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rosgraph_msgs.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import builtin_interfaces_pb2 as builtin__interfaces__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='rosgraph_msgs.proto',
  package='rosgraph_msgs',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x13rosgraph_msgs.proto\x12\rrosgraph_msgs\x1a\x18\x62uiltin_interfaces.proto\"0\n\x05\x43lock\x12\'\n\x05\x63lock\x18\x01 \x01(\x0b\x32\x18.builtin_interfaces.Timeb\x06proto3')
  ,
  dependencies=[builtin__interfaces__pb2.DESCRIPTOR,])




_CLOCK = _descriptor.Descriptor(
  name='Clock',
  full_name='rosgraph_msgs.Clock',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='clock', full_name='rosgraph_msgs.Clock.clock', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=64,
  serialized_end=112,
)

_CLOCK.fields_by_name['clock'].message_type = builtin__interfaces__pb2._TIME
DESCRIPTOR.message_types_by_name['Clock'] = _CLOCK
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Clock = _reflection.GeneratedProtocolMessageType('Clock', (_message.Message,), dict(
  DESCRIPTOR = _CLOCK,
  __module__ = 'rosgraph_msgs_pb2'
  # @@protoc_insertion_point(class_scope:rosgraph_msgs.Clock)
  ))
_sym_db.RegisterMessage(Clock)


# @@protoc_insertion_point(module_scope)
